import type { TableMeta, ColumnMeta } from './types.js';
import { toPascalCase, toCamelCase } from './naming.js';

/**
 * TableMeta[] → hooks.ts 파일 내용 생성
 */
export function generateHooks(tables: TableMeta[]): string {
  const lines: string[] = [
    '// Auto-generated by codegen-db — DO NOT EDIT',
    '',
    "import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';",
  ];

  // import types
  const typeImports: string[] = [];
  for (const table of tables) {
    const pascal = toPascalCase(table.name);
    typeImports.push(`${pascal}Row`, `${pascal}Insert`, `${pascal}Update`);
  }
  lines.push(`import type { ${typeImports.join(', ')} } from './types';`);
  lines.push("import { dbKeys } from './queryKeys';");
  lines.push('');

  for (const table of tables) {
    const pascal = toPascalCase(table.name);
    const camel = toCamelCase(table.name);
    const fqn = `${table.schema}.${table.name}`; // fully qualified name
    const pk = table.columns.find((c) => c.isPrimaryKey);
    const insertCols = table.columns.filter(
      (c) => !c.isPrimaryKey && !c.hasDefault,
    );

    // ── useXxxList ──
    lines.push(`// ── ${pascal} ──────────────────────────────────────`);
    lines.push('');
    lines.push(`export function use${pascal}List() {`);
    lines.push('  return useQuery({');
    lines.push(`    queryKey: dbKeys.${camel}.all,`);
    lines.push(`    queryFn: () =>`);
    lines.push(`      window.electronApi.dbApi.query<${pascal}Row>(`);
    if (pk) {
      lines.push(
        `        'SELECT * FROM ${fqn} ORDER BY ${pk.name} DESC',`,
      );
    } else {
      lines.push(`        'SELECT * FROM ${fqn}',`);
    }
    lines.push('      ),');
    lines.push('  });');
    lines.push('}');
    lines.push('');

    // ── useXxxById ── (PK가 있을 때만)
    if (pk) {
      const pkTs = inferPkTsType(pk.pgType);
      lines.push(`export function use${pascal}ById(id: ${pkTs}) {`);
      lines.push('  return useQuery({');
      lines.push(`    queryKey: dbKeys.${camel}.byId(id),`);
      lines.push('    queryFn: async () => {');
      lines.push(
        `      const rows = await window.electronApi.dbApi.query<${pascal}Row>(`,
      );
      lines.push(
        `        'SELECT * FROM ${fqn} WHERE ${pk.name} = $1',`,
      );
      lines.push('        [id],');
      lines.push('      );');
      lines.push('      return rows[0] ?? null;');
      lines.push('    },');
      lines.push('    enabled: id != null,');
      lines.push('  });');
      lines.push('}');
      lines.push('');
    }

    // ── useInsertXxx ──
    lines.push(`export function useInsert${pascal}() {`);
    lines.push('  const qc = useQueryClient();');
    lines.push('  return useMutation({');
    lines.push(`    mutationFn: (input: ${pascal}Insert) =>`);
    lines.push('      window.electronApi.dbApi.query(');
    lines.push(
      `        '${buildInsertSql(fqn, insertCols)}',`,
    );
    lines.push(
      `        [${insertCols.map((c) => `input.${c.name}`).join(', ')}],`,
    );
    lines.push('      ),');
    lines.push(
      `    onSuccess: () => qc.invalidateQueries({ queryKey: dbKeys.${camel}.all }),`,
    );
    lines.push('  });');
    lines.push('}');
    lines.push('');

    // ── useUpdateXxx ── (PK가 있을 때만)
    if (pk) {
      lines.push(`export function useUpdate${pascal}() {`);
      lines.push('  const qc = useQueryClient();');
      lines.push('  return useMutation({');
      lines.push(
        `    mutationFn: ({ ${pk.name}, ...data }: ${pascal}Update & { ${pk.name}: ${inferPkTsType(pk.pgType)} }) => {`,
      );
      lines.push('      const cols = Object.keys(data);');
      lines.push(
        "      const sets = cols.map((c, i) => `${c} = $${i + 2}`).join(', ');",
      );
      lines.push('      return window.electronApi.dbApi.query(');
      lines.push(
        `        \`UPDATE ${fqn} SET \${sets} WHERE ${pk.name} = $1\`,`,
      );
      lines.push(
        `        [${pk.name}, ...Object.values(data)],`,
      );
      lines.push('      );');
      lines.push('    },');
      lines.push(
        `    onSuccess: () => qc.invalidateQueries({ queryKey: dbKeys.${camel}.all }),`,
      );
      lines.push('  });');
      lines.push('}');
      lines.push('');
    }

    // ── useDeleteXxx ── (PK가 있을 때만)
    if (pk) {
      const pkTs = inferPkTsType(pk.pgType);
      lines.push(`export function useDelete${pascal}() {`);
      lines.push('  const qc = useQueryClient();');
      lines.push('  return useMutation({');
      lines.push(`    mutationFn: (${pk.name}: ${pkTs}) =>`);
      lines.push('      window.electronApi.dbApi.query(');
      lines.push(
        `        'DELETE FROM ${fqn} WHERE ${pk.name} = $1',`,
      );
      lines.push(`        [${pk.name}],`);
      lines.push('      ),');
      lines.push(
        `    onSuccess: () => qc.invalidateQueries({ queryKey: dbKeys.${camel}.all }),`,
      );
      lines.push('  });');
      lines.push('}');
      lines.push('');
    }

    // ── useBulkInsertXxx ── (Phase 2-6)
    if (insertCols.length > 0) {
      lines.push(`export function useBulkInsert${pascal}() {`);
      lines.push('  const qc = useQueryClient();');
      lines.push('  return useMutation({');
      lines.push(`    mutationFn: (rows: ${pascal}Insert[]) =>`);
      lines.push('      window.electronApi.dbApi.bulkInsert(');
      lines.push(`        '${fqn}',`);
      lines.push(
        `        [${insertCols.map((c) => `'${c.name}'`).join(', ')}],`,
      );
      lines.push(
        `        rows.map(r => [${insertCols.map((c) => `r.${c.name}`).join(', ')}]),`,
      );
      lines.push('      ),');
      lines.push(
        `    onSuccess: () => qc.invalidateQueries({ queryKey: dbKeys.${camel}.all }),`,
      );
      lines.push('  });');
      lines.push('}');
      lines.push('');
    }
  }

  return lines.join('\n');
}

function buildInsertSql(fqn: string, cols: ColumnMeta[]): string {
  if (cols.length === 0) return `INSERT INTO ${fqn} DEFAULT VALUES`;
  const names = cols.map((c) => c.name).join(', ');
  const placeholders = cols.map((_, i) => `$${i + 1}`).join(', ');
  return `INSERT INTO ${fqn} (${names}) VALUES (${placeholders})`;
}

function inferPkTsType(pgType: string): string {
  if (['int2', 'int4', 'int8', 'serial', 'bigserial'].includes(pgType)) {
    return 'number';
  }
  if (pgType === 'uuid' || pgType === 'text' || pgType === 'varchar') {
    return 'string';
  }
  return 'unknown';
}
