import type { TableMeta } from './types.js';
import { pgToTs } from './mapTypes.js';
import { toPascalCase } from './naming.js';

/**
 * TableMeta[] → types.ts 파일 내용 생성
 */
export function generateTypes(tables: TableMeta[]): string {
  const lines: string[] = [
    '// Auto-generated by codegen-db — DO NOT EDIT',
    '',
  ];

  for (const table of tables) {
    const pascal = toPascalCase(table.name);

    // ── Row 타입 (SELECT 결과) ──
    lines.push(`/** ${table.schema}.${table.name} — Row (SELECT 결과) */`);
    lines.push(`export interface ${pascal}Row {`);
    for (const col of table.columns) {
      const tsType = pgToTs(col.pgType);
      const nullSuffix = col.nullable ? ' | null' : '';
      lines.push(`  ${col.name}: ${tsType}${nullSuffix};`);
    }
    lines.push('}');
    lines.push('');

    // View는 read-only이므로 Insert/Update 타입을 생성하지 않음
    if (table.isView) continue;

    // ── Insert 타입 ──
    lines.push(`/** ${table.schema}.${table.name} — Insert 입력 */`);
    lines.push(`export interface ${pascal}Insert {`);
    for (const col of table.columns) {
      const tsType = pgToTs(col.pgType);
      const optional = col.isPrimaryKey || col.hasDefault || col.nullable;
      const nullSuffix = col.nullable ? ' | null' : '';
      lines.push(
        `  ${col.name}${optional ? '?' : ''}: ${tsType}${nullSuffix};`,
      );
    }
    lines.push('}');
    lines.push('');

    // ── Update 타입 ──
    lines.push(`/** ${table.schema}.${table.name} — Update 입력 */`);
    lines.push(`export type ${pascal}Update = Partial<${pascal}Insert>;`);
    lines.push('');
  }

  return lines.join('\n');
}
