import type { TableMeta } from './types.js';
import { toCamelCase } from './naming.js';

/**
 * TableMeta[] → queryKeys.ts 파일 내용 생성
 */
export function generateQueryKeys(tables: TableMeta[]): string {
  const lines: string[] = [
    '// Auto-generated by codegen-db — DO NOT EDIT',
    '',
    'export const dbKeys = {',
  ];

  for (let i = 0; i < tables.length; i++) {
    const table = tables[i];
    const camel = toCamelCase(table.name);
    const pk = table.columns.find((c) => c.isPrimaryKey);
    const pkTsType = pk ? inferPkTsType(pk.pgType) : 'unknown';

    lines.push(`  ${camel}: {`);
    lines.push(`    all: ['${table.name}'] as const,`);

    // View는 PK가 없으므로 byId를 생성하지 않음
    if (pk && !table.isView) {
      lines.push(
        `    byId: (id: ${pkTsType}) => ['${table.name}', id] as const,`,
      );
    }

    lines.push(`  },`);
  }

  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

function inferPkTsType(pgType: string): string {
  if (['int2', 'int4', 'int8', 'serial', 'bigserial'].includes(pgType)) {
    return 'number';
  }
  if (pgType === 'uuid' || pgType === 'text' || pgType === 'varchar') {
    return 'string';
  }
  return 'unknown';
}
