import fs from 'fs';
import path from 'path';
import { introspect } from './introspect.js';
import { generateTypes } from './generateTypes.js';
import { generateQueryKeys } from './generateQueryKeys.js';
import { generateHooks } from './generateHooks.js';
import type { TableMeta } from './types.js';

// ── CLI 플래그 파싱 ──
const isDryRun = process.argv.includes('--dry-run');
const fixtureArg = process.argv.find((a) => a.startsWith('--fixture='));
const envArg = process.argv.find((a) => a.startsWith('--env='));
const envName = envArg?.split('=')[1] ?? process.env.NODE_ENV ?? 'development';

// ── config 로드 ──
const configPath = path.resolve('codegen-db.config.ts');
const configMod = await import(configPath);
const config = typeof configMod.default === 'function'
  ? configMod.default(envName)
  : configMod.default;

async function main() {
  let tables: TableMeta[];

  if (isDryRun || fixtureArg) {
    // DB 없이 fixture 데이터로 실행
    const fixturePath =
      fixtureArg?.split('=')[1] ??
      path.resolve('tests/fixtures/sample-schema.json');
    console.log(`[codegen-db] dry-run: loading fixture from ${fixturePath}`);
    const raw = fs.readFileSync(fixturePath, 'utf-8');
    tables = JSON.parse(raw) as TableMeta[];
  } else {
    // 실제 DB에서 스키마 조회
    console.log(`[codegen-db] connecting to ${config.connectionString.replace(/:[^:@]+@/, ':***@')}...`);
    tables = await introspect(
      config.connectionString,
      config.schemas,
      config.exclude,
    );
  }

  if (tables.length === 0) {
    console.log('[codegen-db] no tables found. nothing to generate.');
    return;
  }

  console.log(
    `[codegen-db] found ${tables.length} table(s): ${tables.map((t) => `${t.schema}.${t.name}${t.isView ? ' (view)' : ''}`).join(', ')}`,
  );

  const outDir = path.resolve(config.outputDir);

  if (config.groupBySchema) {
    // ── 스키마별 폴더 분리 모드 ──
    const bySchema = groupTablesBySchema(tables);
    const allSchemas: string[] = [];

    for (const [schema, schemaTables] of bySchema) {
      const schemaDir = path.join(outDir, schema);
      fs.mkdirSync(schemaDir, { recursive: true });

      writeGeneratedFiles(schemaDir, schemaTables);
      allSchemas.push(schema);

      console.log(
        `[codegen-db] generated 3 files in ${schemaDir} (${schemaTables.length} table(s))`,
      );
    }

    // ── 루트 index.ts (스키마별 re-export) ──
    if (config.generateIndex) {
      const indexLines: string[] = [
        '// Auto-generated by codegen-db — DO NOT EDIT',
        '',
      ];
      for (const schema of allSchemas) {
        indexLines.push(`export * from './${schema}/types';`);
        indexLines.push(`export * from './${schema}/queryKeys';`);
        indexLines.push(`export * from './${schema}/hooks';`);
      }
      indexLines.push('');
      fs.mkdirSync(outDir, { recursive: true });
      fs.writeFileSync(path.join(outDir, 'index.ts'), indexLines.join('\n'));
      console.log(`[codegen-db] generated root index.ts`);
    }
  } else {
    // ── 단일 폴더 모드 (기존 동작) ──
    fs.mkdirSync(outDir, { recursive: true });
    writeGeneratedFiles(outDir, tables);

    if (config.generateIndex) {
      const indexLines: string[] = [
        '// Auto-generated by codegen-db — DO NOT EDIT',
        '',
        "export * from './types';",
        "export * from './queryKeys';",
        "export * from './hooks';",
        '',
      ];
      fs.writeFileSync(path.join(outDir, 'index.ts'), indexLines.join('\n'));
      console.log(`[codegen-db] generated index.ts`);
    }

    console.log(`[codegen-db] generated 3 files in ${outDir}`);
  }
}

function writeGeneratedFiles(dir: string, tables: TableMeta[]) {
  const typesContent = generateTypes(tables);
  const keysContent = generateQueryKeys(tables);
  const hooksContent = generateHooks(tables);

  fs.writeFileSync(path.join(dir, 'types.ts'), typesContent);
  fs.writeFileSync(path.join(dir, 'queryKeys.ts'), keysContent);
  fs.writeFileSync(path.join(dir, 'hooks.ts'), hooksContent);
}

function groupTablesBySchema(tables: TableMeta[]): Map<string, TableMeta[]> {
  const map = new Map<string, TableMeta[]>();
  for (const t of tables) {
    const arr = map.get(t.schema) ?? [];
    arr.push(t);
    map.set(t.schema, arr);
  }
  return map;
}

main().catch((err) => {
  console.error('[codegen-db] ERROR:', err);
  process.exit(1);
});
